// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsfYq4dWzFNgzutIi0Xh7Y-9s7XfBksPo',
    appId: '1:912363488883:web:31a248608732b8e1eb0c06',
    messagingSenderId: '912363488883',
    projectId: 'isma-df08a',
    authDomain: 'isma-df08a.firebaseapp.com',
    storageBucket: 'isma-df08a.appspot.com',
    measurementId: 'G-3YZ8GJ883D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB22m6CvZzHEWm7kPUxPwJlhm3yrDuwuV0',
    appId: '1:912363488883:android:ded9c25aab278595eb0c06',
    messagingSenderId: '912363488883',
    projectId: 'isma-df08a',
    storageBucket: 'isma-df08a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN8bYdT8dwNqKPLG9mF6XDTfem9h7llZk',
    appId: '1:912363488883:ios:96b800651e735b4ceb0c06',
    messagingSenderId: '912363488883',
    projectId: 'isma-df08a',
    storageBucket: 'isma-df08a.appspot.com',
    androidClientId: '912363488883-q42j9sktghm7ih417462v25m7m1naq2k.apps.googleusercontent.com',
    iosClientId: '912363488883-r29pbeh3kgusqp9ru0jeqgmc2m080s4o.apps.googleusercontent.com',
    iosBundleId: 'com.jakrta.isma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN8bYdT8dwNqKPLG9mF6XDTfem9h7llZk',
    appId: '1:912363488883:ios:96b800651e735b4ceb0c06',
    messagingSenderId: '912363488883',
    projectId: 'isma-df08a',
    storageBucket: 'isma-df08a.appspot.com',
    androidClientId: '912363488883-q42j9sktghm7ih417462v25m7m1naq2k.apps.googleusercontent.com',
    iosClientId: '912363488883-r29pbeh3kgusqp9ru0jeqgmc2m080s4o.apps.googleusercontent.com',
    iosBundleId: 'com.jakrta.isma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsfYq4dWzFNgzutIi0Xh7Y-9s7XfBksPo',
    appId: '1:912363488883:web:79284768e47d6ba7eb0c06',
    messagingSenderId: '912363488883',
    projectId: 'isma-df08a',
    authDomain: 'isma-df08a.firebaseapp.com',
    storageBucket: 'isma-df08a.appspot.com',
    measurementId: 'G-27WTG4CJ20',
  );

}